typedef dx::linalg::Matrix<dx::linalg::ComponentType::F32, 16, 16, dx::linalg::MatrixUse::A, dx::linalg::MatrixScope::Wave> spvCoopMatF32_16x16_A_Wave;
typedef dx::linalg::Matrix<dx::linalg::ComponentType::F16, 16, 16, dx::linalg::MatrixUse::A, dx::linalg::MatrixScope::Wave> spvCoopMatF16_16x16_A_Wave;
typedef dx::linalg::Matrix<dx::linalg::ComponentType::I32, 16, 16, dx::linalg::MatrixUse::A, dx::linalg::MatrixScope::Wave> spvCoopMatI32_16x16_A_Wave;
typedef dx::linalg::Matrix<dx::linalg::ComponentType::U32, 16, 16, dx::linalg::MatrixUse::A, dx::linalg::MatrixScope::Wave> spvCoopMatU32_16x16_A_Wave;

static const uint3 gl_WorkGroupSize = uint3(32u, 1u, 1u);

RWByteAddressBuffer ssbo : register(u0, space0);
RWByteAddressBuffer ssbo_int : register(u1, space0);

void comp_main()
{
    spvCoopMatF32_16x16_A_Wave _24 = spvCoopMatF32_16x16_A_Wave::Load(ssbo, 16, 64, dx::linalg::MatrixLayout::RowMajor, 4);
    spvCoopMatF32_16x16_A_Wave _28 = spvCoopMatF32_16x16_A_Wave::Load(ssbo, 1040, 64, dx::linalg::MatrixLayout::RowMajor, 4);
    spvCoopMatF32_16x16_A_Wave _32 = _24;
    for (uint spvIndex = 0u; spvIndex < _32.Length(); spvIndex++)
    {
        _32.Set(spvIndex, _32.Get(spvIndex) + _28.Get(spvIndex));
    }
    spvCoopMatF32_16x16_A_Wave _35 = _24;
    for (uint spvIndex = 0u; spvIndex < _35.Length(); spvIndex++)
    {
        _35.Set(spvIndex, _35.Get(spvIndex) - _28.Get(spvIndex));
    }
    spvCoopMatF32_16x16_A_Wave _36 = _32;
    for (uint spvIndex = 0u; spvIndex < _36.Length(); spvIndex++)
    {
        _36.Set(spvIndex, _36.Get(spvIndex) * _35.Get(spvIndex));
    }
    spvCoopMatF32_16x16_A_Wave _38 = _36;
    for (uint spvIndex = 0u; spvIndex < _38.Length(); spvIndex++)
    {
        _38.Set(spvIndex, _38.Get(spvIndex) / _28.Get(spvIndex));
    }
    spvCoopMatF32_16x16_A_Wave _42 = _38;
    for (uint spvIndex = 0u; spvIndex < _42.Length(); spvIndex++)
    {
        _42.Set(spvIndex, _42.Get(spvIndex) * ssbo.Load<float>(0));
    }
    spvCoopMatF32_16x16_A_Wave _43 = _42;
    for (uint spvIndex = 0u; spvIndex < _43.Length(); spvIndex++)
    {
        _43.Set(spvIndex, -_43.Get(spvIndex));
    }
    spvCoopMatI32_16x16_A_Wave _54 = _43.Cast<dx::linalg::ComponentType::F16>().Cast<dx::linalg::ComponentType::I32>();
    spvCoopMatI32_16x16_A_Wave _57 = _54;
    for (uint spvIndex = 0u; spvIndex < _57.Length(); spvIndex++)
    {
        _57.Set(spvIndex, _57.Get(spvIndex) + _54.Get(spvIndex));
    }
    spvCoopMatI32_16x16_A_Wave _59 = _57;
    for (uint spvIndex = 0u; spvIndex < _59.Length(); spvIndex++)
    {
        _59.Set(spvIndex, _59.Get(spvIndex) * _54.Get(spvIndex));
    }
    spvCoopMatI32_16x16_A_Wave _64 = _54;
    for (uint spvIndex = 0u; spvIndex < _64.Length(); spvIndex++)
    {
        _64.Set(spvIndex, _64.Get(spvIndex) / _57.Get(spvIndex));
    }
    spvCoopMatI32_16x16_A_Wave _65 = _59;
    for (uint spvIndex = 0u; spvIndex < _65.Length(); spvIndex++)
    {
        _65.Set(spvIndex, _65.Get(spvIndex) - _64.Get(spvIndex));
    }
    spvCoopMatF32_16x16_A_Wave back = _65.Cast<dx::linalg::ComponentType::F32>();
    for (int _128 = 0; _128 < int(spvCoopMatF32_16x16_A_Wave::Splat(0).Length()); )
    {
        float _85 = back.Get(_128);
        back.Set(_128, _85 + 50.0f);
        _128++;
        continue;
    }
    spvCoopMatF32_16x16_A_Wave _124 = back;
    spvCoopMatF32_16x16_A_Wave _125 = _43;
    float _100 = _124.Get(1);
    _125.Set(0, _100);
    _125.Store(ssbo, 2064, 64, dx::linalg::MatrixLayout::RowMajor, 4);
    _65.Store(ssbo_int, 0, 64, dx::linalg::MatrixLayout::RowMajor, 4);
    _65.Cast<dx::linalg::ComponentType::U32>().Store(ssbo_int, 1024, 64, dx::linalg::MatrixLayout::RowMajor, 4);
}

[numthreads(32, 1, 1)]
void main()
{
    comp_main();
}
