; SPIR-V
; Version: 1.3
; Generator: Khronos Glslang Reference Front End; 11
; Bound: 50
; Schema: 0
               OpCapability Shader
               OpCapability Float16
               OpCapability VulkanMemoryModel
               OpCapability CooperativeMatrixKHR
               OpExtension "SPV_KHR_cooperative_matrix"
               OpExtension "SPV_KHR_vulkan_memory_model"
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical Vulkan
               OpEntryPoint GLCompute %4 "main"
               OpExecutionMode %4 LocalSize 32 1 1
               OpSource GLSL 450
               OpSourceExtension "GL_EXT_shader_explicit_arithmetic_types_float16"
               OpSourceExtension "GL_KHR_cooperative_matrix"
               OpSourceExtension "GL_KHR_memory_scope_semantics"
               OpName %4 "main"
               OpName %13 "a"
               OpName %19 "b"
               OpName %25 "c"
               OpName %31 "d"
               OpName %40 "SSBO"
               OpMemberName %40 0 "data"
               OpName %42 "ssbo"
               OpDecorate %39 ArrayStride 4
               OpDecorate %40 Block
               OpMemberDecorate %40 0 Offset 0
               OpDecorate %42 Binding 0
               OpDecorate %42 DescriptorSet 0
               OpDecorate %49 BuiltIn WorkgroupSize
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
          %6 = OpTypeFloat 16
          %7 = OpTypeInt 32 0
          %8 = OpConstant %7 3
          %9 = OpConstant %7 16
         %10 = OpConstant %7 0
         %11 = OpTypeCooperativeMatrixKHR %6 %8 %9 %9 %10
         %12 = OpTypePointer Function %11
         %14 = OpConstant %6 0x1p+0
         %15 = OpConstantComposite %11 %14
         %16 = OpConstant %7 1
         %17 = OpTypeCooperativeMatrixKHR %6 %8 %9 %9 %16
         %18 = OpTypePointer Function %17
         %20 = OpConstant %6 0x1p+1
         %21 = OpConstantComposite %17 %20
         %22 = OpConstant %7 2
         %23 = OpTypeCooperativeMatrixKHR %6 %8 %9 %9 %22
         %24 = OpTypePointer Function %23
         %26 = OpConstant %6 0x1p-1
         %27 = OpConstantComposite %23 %26
         %28 = OpTypeFloat 32
         %29 = OpTypeCooperativeMatrixKHR %28 %8 %9 %9 %22
         %30 = OpTypePointer Function %29
         %39 = OpTypeRuntimeArray %28
         %40 = OpTypeStruct %39
         %41 = OpTypePointer StorageBuffer %40
         %42 = OpVariable %41 StorageBuffer
         %43 = OpTypeInt 32 1
         %44 = OpConstant %43 0
         %45 = OpTypePointer StorageBuffer %28
         %47 = OpTypeVector %7 3
         %48 = OpConstant %7 32
         %49 = OpConstantComposite %47 %48 %16 %16
          %4 = OpFunction %2 None %3
          %5 = OpLabel
         %13 = OpVariable %12 Function
         %19 = OpVariable %18 Function
         %25 = OpVariable %24 Function
         %31 = OpVariable %30 Function
               OpStore %13 %15
               OpStore %19 %21
               OpStore %25 %27
         %32 = OpLoad %23 %25
         %34 = OpLoad %11 %13
         %35 = OpLoad %17 %19
         %37 = OpCooperativeMatrixMulAddKHR %29 %34 %35 %32
               OpStore %31 %37
         %38 = OpLoad %29 %31
         %46 = OpAccessChain %45 %42 %44 %10
               OpCooperativeMatrixStoreKHR %46 %38 %44 %9 None
               OpReturn
               OpFunctionEnd
